presubmits:
  kubernetes-incubator/service-catalog:
  - name: pull-service-catalog-unit
    agent: kubernetes
    context: pull-service-catalog-unit
    always_run: true
    skip_report: false
    rerun_command: "/test pull-service-catalog-unit"
    trigger: "(?m)^/test (all|pull-service-catalog-unit)\\s*"
    decorate: true
    spec:
      containers:
      - image: golang:1.10
        command:
        - make
        args:
        - test-unit
        env:
        - name: NO_DOCKER
          value: "1"
  - name: pull-service-catalog-integration
    agent: kubernetes
    context: pull-service-catalog-integration
    always_run: true
    skip_report: false
    rerun_command: "/test pull-service-catalog-integration"
    trigger: "(?m)^/test (all|pull-service-catalog-integration)\\s*"
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180716-9145034c9-1.10
        args:
        - "--repo=github.com/kubernetes-incubator/$(REPO_NAME)=$(PULL_REFS)"
        - "--timeout=45"
        - "--scenario=execute"
        - "--"
        - "make"
        - "test-integration"
        env:
        - name: DOCKER_IN_DOCKER_ENABLED
          value: "true"
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        # docker-in-docker needs a place to store the images
        volumeMounts:
          - name: docker-graph
            mountPath: /docker-graph
      volumes:
        - name: docker-graph
          emptyDir: {}
  - name: pull-service-catalog-xbuild
    agent: kubernetes
    context: pull-service-catalog-xbuild
    always_run: true
    skip_report: false
    rerun_command: "/test pull-service-catalog-xbuild"
    trigger: "(?m)^/test (all|pull-service-catalog-xbuild)\\s*"
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180725-795cceb4c-1.10
        args:
        - "--repo=github.com/kubernetes-incubator/$(REPO_NAME)=$(PULL_REFS)"
        - "--timeout=60"
        - "--scenario=execute"
        - "--"
        - "make"
        - "images-all"
        - "svcat-all"
        env:
        - name: DOCKER_IN_DOCKER_ENABLED
          value: "true"
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        # docker-in-docker needs a place to store the images
        volumeMounts:
          - name: docker-graph
            mountPath: /docker-graph
      volumes:
        - name: docker-graph
          emptyDir: {}
