presubmits:
  kubernetes-sigs/gcp-compute-persistent-disk-csi-driver:
  - name: pull-gcp-compute-persistent-disk-csi-driver-e2e
    context: pull-gcp-compute-persistent-disk-csi-driver-e2e
    always_run: true
    rerun_command: "/test pull-gcp-compute-persistent-disk-csi-driver-e2e"
    trigger: "(?m)^/test( all| pull-gcp-compute-persistent-disk-csi-driver-e2e),?(\\s+|$)"
    agent: kubernetes
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/gcloud-in-go:v20171113-192bec25
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=300"
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "test/run-e2e.sh"
        env:
        - name: ZONE
          value: us-central1-c
  - name: pull-gcp-compute-persistent-disk-csi-driver-sanity
    context: pull-gcp-compute-persistent-disk-csi-driver-sanity
    always_run: true
    rerun_command: "/test pull-gcp-compute-persistent-disk-csi-driver-sanity"
    trigger: "(?m)^/test( all| pull-gcp-compute-persistent-disk-csi-driver-sanity),?(\\s+|$)"
    agent: kubernetes
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/gcloud-in-go:v20171113-192bec25
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=10"
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "test/run-sanity.sh"
  - name: pull-gcp-compute-persistent-disk-csi-driver-unit
    context: pull-gcp-compute-persistent-disk-csi-driver-unit
    always_run: true
    rerun_command: "/test pull-gcp-compute-persistent-disk-csi-driver-unit"
    trigger: "(?m)^/test( all| pull-gcp-compute-persistent-disk-csi-driver-unit),?(\\s+|$)"
    agent: kubernetes
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/gcloud-in-go:v20171113-192bec25
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=10"
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "test/run-unit.sh"
  - name: pull-gcp-compute-persistent-disk-csi-driver-verify
    context: pull-gcp-compute-persistent-disk-csi-driver-verify
    always_run: true
    rerun_command: "/test pull-gcp-compute-persistent-disk-csi-driver-verify"
    trigger: "(?m)^/test( all| pull-gcp-compute-persistent-disk-csi-driver-verify),?(\\s+|$)"
    agent: kubernetes
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/gcloud-in-go:v20171113-192bec25
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=10"
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "hack/verify-all.sh"
