presubmits:
  kubeflow/examples:
  - name: kubeflow-examples-presubmit
    context: kubeflow-examples-presubmit
    agent: kubernetes
    always_run: true         # Run for every PR, or only when requested.
    rerun_command: "/test kubeflow-examples-presubmit"
    trigger: "(?m)^/test( all| kubeflow-examples-presubmit),?(\\s+|$)"
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/kubeflow:
  - name: kubeflow-presubmit
    context: kubeflow-presubmit
    agent: kubernetes
    always_run: true         # Run for every PR, or only when requested.
    rerun_command: "/test kubeflow-presubmit"
    trigger: "(?m)^/test( all| kubeflow-presubmit),?(\\s+|$)"
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/pytorch-operator:
  - name: kubeflow-pytorch-operator-presubmit
    context: kubeflow-pytorch-operator-presubmit
    agent: kubernetes
    always_run: true         # Run for every PR, or only when requested.
    rerun_command: "/test kubeflow-pytorch-operator-presubmit"
    trigger: "(?m)^/test( all| kubeflow-pytorch-operator-presubmit),?(\\s+|$)"
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/reporting:
  - name: kubeflow-reporting-presubmit
    context: kubeflow-reporting-presubmit
    agent: kubernetes
    always_run: true         # Run for every PR, or only when requested.
    rerun_command: "/test kubeflow-reporting-presubmit"
    trigger: "(?m)^/test( all| kubeflow-reporting-presubmit),?(\\s+|$)"
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/website:
  - name: kubeflow-website-presubmit
    context: kubeflow-website-presubmit
    agent: kubernetes
    always_run: true         # Run for every PR, or only when requested.
    rerun_command: "/test kubeflow-website-presubmit"
    trigger: "(?m)^/test( all| kubeflow-website-presubmit),?(\\s+|$)"
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/testing:
  - name: kubeflow-testing-presubmit
    context: kubeflow-testing-presubmit
    agent: kubernetes
    always_run: true         # Run for every PR, or only when requested.
    rerun_command: "/test kubeflow-testing-presubmit"
    trigger: "(?m)^/test( all| kubeflow-testing-presubmit),?(\\s+|$)"
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/tf-operator:
  - name: kubeflow-tf-operator-presubmit
    context: kubeflow-tf-operator-presubmit
    agent: kubernetes
    always_run: true         # Run for every PR, or only when requested.
    rerun_command: "/test kubeflow-tf-operator-presubmit"
    trigger: "(?m)^/test( all| kubeflow-tf-operator-presubmit),?(\\s+|$)"
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/katib:
  - name: kubeflow-katib-presubmit
    context: kubeflow-katib-presubmit
    agent: kubernetes
    always_run: true         # Run for every PR, or only when requested.
    rerun_command: "/test kubeflow-katib-presubmit"
    trigger: "(?m)^/test( all| kubeflow-katib-presubmit),?(\\s+|$)"
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/experimental-kvc:
  - name: kubeflow-experimental-kvc-presubmit
    context: kubeflow-experimental-kvc-presubmit
    agent: kubernetes
    always_run: true         # Run for every PR, or only when requested.
    rerun_command: "/test kubeflow-experimental-kvc-presubmit"
    trigger: "(?m)^/test( all| kubeflow-experimental-kvc-presubmit),?(\\s+|$)"
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/experimental-seldon:
  - name: kubeflow-experimental-seldon-presubmit
    context: kubeflow-experimental-seldon-presubmit
    agent: kubernetes
    always_run: true         # Run for every PR, or only when requested.
    rerun_command: "/test kubeflow-experimental-seldon-presubmit"
    trigger: "(?m)^/test( all| kubeflow-experimental-seldon-presubmit),?(\\s+|$)"
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/experimental-beagle:
  - name: kubeflow-experimental-beagle-presubmit
    context: kubeflow-experimental-beagle-presubmit
    agent: kubernetes
    always_run: true         # Run for every PR, or only when requested.
    rerun_command: "/test kubeflow-experimental-beagle-presubmit"
    trigger: "(?m)^/test( all| kubeflow-experimental-beagle-presubmit),?(\\s+|$)"
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/caffe2-operator:
  - name: kubeflow-caffe2-operator-presubmit
    context: kubeflow-caffe2-operator-presubmit
    agent: kubernetes
    always_run: true         # Run for every PR, or only when requested.
    rerun_command: "/test kubeflow-caffe2-operator-presubmit"
    trigger: "(?m)^/test( all| kubeflow-caffe2-operator-presubmit),?(\\s+|$)"
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/kubebench:
  - name: kubeflow-kubebench-presubmit
    context: kubeflow-kubebench-presubmit
    agent: kubernetes
    always_run: true         # Run for every PR, or only when requested.
    rerun_command: "/test kubeflow-kubebench-presubmit"
    trigger: "(?m)^/test( all| kubeflow-kubebench-presubmit),?(\\s+|$)"
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/mpi-operator:
  - name: kubeflow-mpi-operator-presubmit
    context: kubeflow-mpi-operator-presubmit
    agent: kubernetes
    always_run: true         # Run for every PR, or only when requested.
    rerun_command: "/test kubeflow-mpi-operator-presubmit"
    trigger: "(?m)^/test( all| kubeflow-mpi-operator-presubmit),?(\\s+|$)"
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always
