postsubmits:
  kubeflow/examples:
  - name: kubeflow-examples-postsubmit
    agent: kubernetes
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/kubeflow:
  - name: kubeflow-postsubmit
    agent: kubernetes
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/pytorch-operator:
  - name: kubeflow-pytorch-operator-postsubmit
    agent: kubernetes
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/reporting:
  - name: kubeflow-reporting-postsubmit
    agent: kubernetes
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/website:
  - name: kubeflow-website-postsubmit
    agent: kubernetes
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/testing:
  - name: kubeflow-testing-postsubmit
    agent: kubernetes
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/tf-operator:
  - name: kubeflow-tf-operator-postsubmit
    agent: kubernetes
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/katib:
  - name: kubeflow-katib-postsubmit
    agent: kubernetes
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/experimental-kvc:
  - name: kubeflow-experimental-kvc-postsubmit
    agent: kubernetes
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/experimental-seldon:
  - name: kubeflow-experimental-seldon-postsubmit
    agent: kubernetes
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/experimental-beagle:
  - name: kubeflow-experimental-beagle-postsubmit
    agent: kubernetes
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/caffe2-operator:
  - name: kubeflow-caffe2-operator-postsubmit
    agent: kubernetes
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/kubebench:
  - name: kubeflow-kubebench-postsubmit
    agent: kubernetes
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/mpi-operator:
  - name: kubeflow-mpi-operator-postsubmit
    agent: kubernetes
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always
