presets:
- labels:
    preset-cadvisor-docker-credential: "true"
  env:
  - name: DOCKER_USER
    value: /etc/cadvisor-cred/username
  - name: DOCKER_PASSWORD
    value: /etc/cadvisor-cred/password
  volumes:
  - name: cadvisor-cred
    secret:
      defaultMode: 0400
      secretName: cadvisor-docker-credential
  volumeMounts:
  - name: cadvisor-cred
    mountPath: /etc/cadvisor-cred
    readOnly: true

presubmits:
  google/cadvisor:
  - name: pull-cadvisor-e2e
    agent: kubernetes
    always_run: true
    context: pull-cadvisor-e2e
    rerun_command: "/test pull-cadvisor-e2e"
    trigger: "(?m)^/test( all| pull-cadvisor-e2e),?(\\s+|$)"
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180725-795cceb4c-master
        args:
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/kubernetes"
        - "--repo=github.com/$(REPO_OWNER)/$(REPO_NAME)=$(PULL_REFS)"
        - --root=/go/src
        - --service-account=/etc/service-account/service-account.json
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --timeout=90
        - --scenario=kubernetes_e2e
        - --
        - --deployment=node
        - --gcp-project=cadvisor-e2e
        - --gcp-zone=us-central1-f
        - --node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/image-config.yaml --test-suite=cadvisor
        - --node-tests=true
        - --provider=gce
        - --test_args=--nodes=1--flakeAttempts=2
        - --timeout=10m

periodics:
- interval: 24h
  name: ci-cadvisor-canarypush
  agent: kubernetes
  labels:
    preset-service-account: "true"
    preset-cadvisor-docker-credential: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/bootstrap:v20180510-809cd85b5
      args:
      - --repo=github.com/google/cadvisor
      - --root=/go/src
      - --timeout=30
      - --scenario=canarypush
      - --
      - --file=deploy/canary/Dockerfile
      - --owner=stclair@google.com
      - --target=google/cadvisor:canary
      env:
      - name: DOCKER_IN_DOCKER_ENABLED
        value: "true"
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      volumeMounts:
      - name: docker-graph
        mountPath: /docker-graph
    volumes:
    - name: docker-graph
      emptyDir: {}

- name: ci-cadvisor-e2e
  interval: 8h
  agent: kubernetes
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20180725-795cceb4c-master
      args:
      - --job=$(JOB_NAME)
      - --root=/go/src
      - --repo=k8s.io/kubernetes
      - --repo=github.com/google/cadvisor=master
      - --service-account=/etc/service-account/service-account.json
      - --timeout=90
      - --upload=gs://kubernetes-jenkins/logs
      - --scenario=kubernetes_e2e
      - --
      - --deployment=node
      - --gcp-project=ci-cadvisor-e2e
      - --gcp-zone=us-central1-f
      - --node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/image-config.yaml --test-suite=cadvisor
      - --node-tests=true
      - --provider=gce
      - --test_args=--nodes=1--flakeAttempts=2
      - --timeout=10m
      env:
      - name: GOPATH
        value: /go
