# basic config options.
app: misc-mungers
http-cache-dir: /cache/httpcache
organization: kubernetes
project: kubernetes
pr-mungers: label-unapproved-picks,path-label,stale-green-ci,comment-deleter,milestone-maintainer
state: open
token-file: /etc/secret-volume/token
period: 60s
repo-dir: /gitrepos
github-key-file: /etc/hook-secret-volume/secret

# status context options.
# Please keep these lists in sorted order.
# !!! This *MUST* be kept in sync with
#     ../../../submit-queue/deployment/kubernetes/configmap.yaml !!!
required-retest-contexts: "\
  pull-kubernetes-bazel-build,\
  pull-kubernetes-bazel-test,\
  pull-kubernetes-e2e-gce,\
  pull-kubernetes-e2e-gce-100-performance,\
  pull-kubernetes-e2e-kops-aws,\
  pull-kubernetes-integration,\
  pull-kubernetes-kubemark-e2e-gce-big,\
  pull-kubernetes-node-e2e,\
  pull-kubernetes-typecheck,\
  pull-kubernetes-verify"

# munger specific options.
path-label-config: "/etc/munge-config/path-label.txt"
number-of-old-test-results: 5
generated-files-config: .generated_files
label-file: "/gitrepos/kubernetes/labels.yaml"
alias-file: "/gitrepos/kubernetes/OWNERS_ALIASES"
use-reviewers: true
# milestone-maintainer
milestone-modes: v1.8=dev,v1.9=dev,v1.10=dev,v1.11=dev,v1.12=dev
milestone-freeze-date: "TBD"
milestone-approval-grace-period: 96h
