presubmits:
  kubernetes/cloud-provider-gcp:
  - name: cloud-provider-gcp-tests
    agent: kubernetes
    max_concurrency: 5
    always_run: true
    context: cloud-provider-gcp-tests
    rerun_command: "/test cloud-provider-gcp-tests"
    trigger: "(?m)^/test( all| cloud-provider-gcp-tests),?(\\s+|$)"
    decorate: true
    spec:
      containers:
      - image: gcr.io/cloud-builders/bazel
        command: ["bash"]
        args:
        - -c
        - |
          bazel --output_base=/tmp build -- //... -//vendor/... && \
          bazel --output_base=/tmp test --test_output=errors -- //... -//vendor/...
