presubmits:
  kubernetes/test-infra:
  - name: pull-test-infra-bazel
    agent: kubernetes
    context: pull-test-infra-bazel
    branches:
    - master
    always_run: true
    rerun_command: "/test pull-test-infra-bazel"
    trigger: "(?m)^/test( all| pull-test-infra-bazel),?(\\s+|$)"
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180725-795cceb4c-experimental
        args:
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--service-account=/etc/service-account/service-account.json"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--scenario=kubernetes_execute_bazel"
        - "--timeout=15"
        - "--" # end bootstrap args, scenario args below
        - "hack/build-then-unit.sh"
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "2Gi"

  - name: pull-test-infra-gubernator
    agent: kubernetes
    context: pull-test-infra-gubernator
    branches:
    - master
    rerun_command: "/test pull-test-infra-gubernator"
    trigger: "(?m)^/test pull-test-infra-gubernator,?(\\s+|$)"
    run_if_changed: 'gubernator|prow/config.yaml'
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/gubernator:0.4
        args:
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --service-account=/etc/service-account/service-account.json
        - --scenario=execute
        - --
        - ./gubernator/test-gubernator.sh

  - name: pull-test-infra-lint
    agent: kubernetes
    context: pull-test-infra-lint
    always_run: true
    rerun_command: "/test pull-test-infra-lint"
    trigger: "(?m)^/test( all| pull-test-infra-lint),?(\\s+|$)"
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:latest-experimental
        imagePullPolicy: Always
        args:
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--service-account=/etc/service-account/service-account.json"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--scenario=kubernetes_bazel"
        - "--timeout=15"
        - "--" # end bootstrap args, scenario args below
        - "--install=gubernator/test_requirements.txt"
        - "--test=//..."
        - "--test-args=--config=lint"
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        volumeMounts:
        resources:
          requests:
            memory: "2Gi"

  - name: pull-test-infra-verify-bazel
    agent: kubernetes
    context: pull-test-infra-verify-bazel
    branches:
    - master
    rerun_command: "/test pull-test-infra-verify-bazel"
    trigger: "(?m)^/test( all| pull-test-infra-verify-bazel),?(\\s+|$)"
    always_run: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/gcloud-in-go:v20171113-192bec25
        args:
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - --root=/go/src
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --scenario=execute
        - --
        - ./hack/verify-bazel.sh

  - name: pull-test-infra-verify-config
    agent: kubernetes
    context: pull-test-infra-verify-config
    branches:
    - master
    rerun_command: "/test pull-test-infra-verify-config"
    trigger: "/test pull-test-infra-verify-config"
    run_if_changed: '^prow/config.yaml$'
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180725-795cceb4c-experimental
        args:
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --service-account=/etc/service-account/service-account.json
        - --timeout=15
        - --scenario=execute
        - --
        - ./hack/verify-config.sh
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "2Gi"

  - name: pull-test-infra-verify-config-canary
    agent: kubernetes
    context: pull-test-infra-verify-config-canary
    branches:
    - master
    rerun_command: "/test pull-test-infra-verify-config-canary"
    trigger: "/test pull-test-infra-verify-config-canary"
    path_alias: "k8s.io/test-infra"
    decorate: true
    spec:
      containers:
      - name: test
        command:
        - ./hack/verify-config.sh
        image: gcr.io/k8s-testimages/kubekins-e2e:v20180725-795cceb4c-experimental
        env:
        - name: TEST_TMPDIR
          value: /bazel-scratch/.cache/bazel
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "2Gi"
        volumeMounts:
        - name: bazel-scratch
          mountPath: /bazel-scratch/.cache
      volumes:
      - name: bazel-scratch
        emptyDir: {}

  - name: pull-test-infra-verify-deps
    agent: kubernetes
    context: pull-test-infra-verify-deps
    branches:
    - master
    rerun_command: "/test pull-test-infra-verify-deps"
    trigger: "/test pull-test-infra-verify-deps"
    run_if_changed: '^(Gopkg\.|^vendor/).*$'
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180725-795cceb4c-experimental
        args:
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --service-account=/etc/service-account/service-account.json
        - --scenario=execute
        - --
        - ./hack/verify-deps.sh
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "2Gi"

  - name: pull-test-infra-verify-codegen
    agent: kubernetes
    context: pull-test-infra-verify-codegen
    branches:
    - master
    rerun_command: "/test pull-test-infra-verify-codegen"
    trigger: "/test pull-test-infra-verify-codegen"
    run_if_changed: '(prow/(apis|client)|vendor)/.*$'
    path_alias: "k8s.io/test-infra"
    optional: true
    decorate: true
    spec:
      containers:
      - image: docker.io/library/golang:1.10
        command:
        - ./hack/verify-codegen.sh
        resources:
          requests:
            memory: "2Gi"

  - name: pull-test-infra-verify-gofmt
    agent: kubernetes
    context: pull-test-infra-verify-gofmt
    branches:
    - master
    rerun_command: "/test pull-test-infra-verify-gofmt"
    trigger: "/test( all| pull-test-infra-verify-gofmt)"
    always_run: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/gcloud-in-go:v20171113-192bec25
        args:
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - --root=/go/src
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --scenario=execute
        - --
        - ./hack/verify-gofmt.sh

  - name: pull-test-infra-verify-govet
    agent: kubernetes
    context: pull-test-infra-verify-govet
    branches:
    - master
    rerun_command: "/test pull-test-infra-verify-govet"
    trigger: "/test( all| pull-test-infra-verify-govet)"
    always_run: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/gcloud-in-go:v20171113-192bec25
        args:
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - --root=/go/src
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --scenario=execute
        - --
        - ./hack/verify-govet.sh

  - name: pull-test-infra-verify-labels
    agent: kubernetes
    context: pull-test-infra-verify-labels
    branches:
    - master
    rerun_command: "/test pull-test-infra-verify-labels"
    trigger: "/test pull-test-infra-verify-labels"
    run_if_changed: '^label_sync'
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180725-795cceb4c-experimental
        args:
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - --root=/go/src
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --service-account=/etc/service-account/service-account.json
        - --scenario=execute
        - --
        - ./hack/verify-labels.sh
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "2Gi"
